- README.md
For now this process will be manual so this PR adds documentation for whenever we want to release a new version of the Golang package.
> chore: add docs about release process

- terraform/constants.go
- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/schemas.go
- terraform/variables.go
This is done to help on our vision to create better TF support for our product and find more issues that might have been ignored so far because they would be coming from variable values.
This PR is to support input variables, with or without default values. 
In the [Decision Document](https://www.notion.so/snyk/Terraform-Variable-Dereferencing-in-the-Snyk-CLI-24c2c15f5a0942429b7454b0796a4298), we decided to create a new library in Go where the implementation for this would live.
We already have played [a spike](https://www.notion.so/snyk/POC-Golang-based-Terraform-var-dereferencing-and-Terraform-to-JSON-conversion-with-merging-all-cont-cc931b9f965347ab826f0b7076b676cf#9e93f530bb1f4d74bd85055a706b948e) on how this could look like.
We plan to build a parser that can deal with (end goal):
- …
> Feat: Added inputs variables dereferencing support [CFG-1501]

- terraform/constants.go
- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/utils.go
- terraform/utils_test.go
- terraform/variables.go
- terraform/variables_test.go
This PR enables support for dereferencing variables defined in`terraform.tfvars` and `*.auto.tfvars` . It does not aim to support `terraform.tfvars.json` and `*.auto.tfvars.json` files, or files provided via the `-var` and `-var-file`flags. Tfvars files are explained [here](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files)
It keeps in mind variable definition precedences, as per [this](https://www.terraform.io/language/values/variables#variable-definition-precedence) doc. So default variables can be overridden by `terraform.tfvars` variables, then by `*.auto.tfvars` variables with the last file in alphabetical order overriding everything (if already defined).
The `ParseModule` was modified so that files ending in `.tf` and `.tfvars` have variables …
> feat: dereference variables from terraform.tfvars and *.auto.tfvars [CFG-1502]

- terraform/errors.go
- terraform/errors_test.go
- terraform/hcl2json.go
- terraform/hcl2json_test.go
This PR exposes a new return value from the `ParseModule` function, namely `debugLogs`. This contains extra debugging logs from the parsing, split by file name. The logs can be used in the `snyk` CLI to provide more context to the user about the error.
The debug logs are only populated for user errors, which we consider actionable.
[CFG-1582](https://snyksec.atlassian.net/browse/CFG-1582)
> feat: add debugging logs [CFG-1582]

- terraform/variables_test.go
In https://github.com/snyk/snyk-iac-parsers/pull/12 the tests passed randomly that one time the pipeline run but then in `main` branch they failed. The test being deleted in this PR was testing something that was never going to happen. The reason it sometimes fails and sometimes doesn't is because of the `sort.Slice` logic in the file prioritisation function - depending on the order it goes through the files, the `sort.Slice` might put random `.tfvars` files before or after valid `.tf` files.
One way to fix this would be to add a lot of `if` statements throughout the code to check if invalid variable files are provided (e.g. `test.tfvars`) but in `ParseModule` we already filter those out. I don't see the point in doing this.
> test: remove redundant test

- .circleci/config.yml
- terraform/fixtures/a.auto.tfvars
- terraform/fixtures/b.auto.tfvars
- terraform/fixtures/terraform.tfvars
- terraform/fixtures/test.tf
- terraform/fixtures/variables.tf
- terraform/hcl2json_test.go
- terraform/utils.go
- terraform/utils_test.go
The Windows acceptance tests in `snyk` started failing. It was hard to tell why so I printed the parsed files in a branch and I could see from the output of the failing test that the file names use `\\` instead of `/`, which is used as a condition in our code to parse `terraform.tfvars` files: https://app.circleci.com/pipelines/github/snyk/snyk/10160/workflows/cca75d6f-b978-4bca-a934-09b0b0a9b7f2/jobs/78772
This PR adds a step to CircleCI to run Windows tests, modifies one of the tests to read from the filesystem and so mimic the `snyk` behaviour, and fixes the issue by using `os.PathSeparator` instead of `/`.
The added fixture files are just a copy-paste of the inline tests.
> fix: path separator for windows

- terraform/utils.go
- terraform/utils_test.go
In https://github.com/snyk/snyk-iac-parsers/pull/14 I tried to fix an issue where file paths from Windows scans (looking like `C:\\\\Users\\\\circleci\\\\snyk\\\\test\\\\fixtures\\\\iac\\\\terraform\\\\var_deref\\\\terraform.tfvars`) wouldn't identify the `terraform.tfvars` file as valid because we were always trying to find a file with the suffix `/terraform.tfvars`.
I added a Windows test which exemplified the problem but I hadn't tested it with the CLI directly and so I didn't realise that it wouldn't actually fix it. The reason it doesn't fix it is because we use `gopherjs` to compile the code to JavaScript, with `GOOS=linux`: https://github.com/snyk/snyk/blob/master/release-scripts/hcl-to-json-parser-generator-v2/Makefile#L33
As …
> fix: tfvars path windows replace

- .circleci/config.yml
For https://snyksec.atlassian.net/browse/CFG-1594 I was checking that we had the security scanning configured for this repo by comparing its CircleCI setup with the one in `snyk-iac-rules`. So this PR does whatever this PR did: https://github.com/snyk/snyk-iac-rules/pull/120
> chore: use circle context for env

- catalog-info.yaml
Used by the Snyk organization via backstage.io to manage our service catalog. 
- the `metadata.labels["snyk.io/businessCriticality"]` was set to `medium` because this is used by the SCM and CLI so it could affect the responses given to customers there, but it doesn't stop us doing business (open to discussion)
- the `metadata.labels["snyk.io/metadata-version"]` was set based on the validation tool
- the `spec.owner` was  set based on  the validation tool
Validation using https://github.com/snyk/prodsec-github-bot:
Ticket: https://snyksec.atlassian.net/browse/CFG-1593
> chore: add service catalog to the repository [CFG-1593]

- scripts/opa/main.go
- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/parser.go
- terraform/utils.go
- terraform/utils_test.go
- terraform/variables.go
- terraform/variables_test.go
- Refactors types for storing input values, local values, and TF variables in the `terraform` package.
This change helps clarify the contents of different variable-related structs and maps in our current parser's flow.
- Renames several functions and types with the `variable` term, to use the term `input` instead.
This change helps gain better distinguishment between inputs and locals in the code, as both are considered variables in Terraform.
- [CFG-1500](https://snyksec.atlassian.net/browse/CFG-1500)
> Refactor: Rename variables to inputs [CFG-1500]

- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/variables.go
- Extracts the flow steps of the `ParseModule` into separate functions.
- Adds struct types for files and the parser result.
- Instead of the `hclsyntax.ParseConfig` function getting called for each step, it is now called once at the beginning of the flow.
- [CFG-1500](https://snyksec.atlassian.net/browse/CFG-1500)
> Refactor: Extract `ParseModule` flow steps to functions [CFG-1500]

- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/parser.go
- terraform/schemas.go
- terraform/utils.go
- terraform/variables.go
- Adds support for dereferencing local variables during parsing, including:
- Expressions evaluation during the dereferencing.
- Correctly evaluate locals with input values references.
- Correctly evaluate locals with other local values references.
We would like to start supporting reading variable values in Terraform files. This is to help on our vision to create better TF support for our product and find more issues that might have been ignored so far because they would be coming from variable values. This PR is for adding support for local values.
- [CFG-1500](https://snyksec.atlassian.net/browse/CFG-1500)
- [Terraform - Local values](https://www.terraform.io/language/values/locals)
> Feat: Add TF locals support [CFG-1500]

- .github/workflows/release.yml
- .gitignore
- .release-it.json
- README.md
This adds an automated release process using [release-it](https://github.com/release-it/release-it) for creating the GitHub release.
Because `release-it` generates new tags/releases for `chore:` commits too (see https://github.com/release-it/release-it/issues/783), we are using https://github.com/caarlos0/svu to generate tags and conditionally create releases. The same way we do in [snyk-iac-rules](https://github.com/snyk/snyk-iac-rules/blob/develop/.github/workflows/release.yml).
I've run some tests by changing the branch to the current one. See screenshots.
Example run for `chore:` to prove that semver works: https://github.com/snyk/snyk-iac-parsers/actions/runs/1951239680
Example run for `feat:` to prove that semver works: https://github.com/snyk/snyk-iac-parsers/runs/5463892569?check_s …
> chore: add automated release process

- terraform/hcl2json.go
- terraform/hcl2json_test.go
- terraform/parser.go
- terraform/parser_test.go
- terraform/variables.go
- terraform/variables_test.go
Following the [PR where we added support for local values](https://github.com/snyk/snyk-iac-parsers/pull/18), we would like to add support for local values that reference other local values.
There are multiple methods to achieve this functionality, this PR implements the brute-force method which is very similar to tf-sec's implementation.
We are iterating through the local values and using the available context we are trying to dereference each local value, if we managed to successfully dereference the value we add it context to our available context.
The loop will stop in two cases, if we reach the maximum allowed iterations or if the context from the last iteration is equal to the current context (or in other words, in the latest iteration we didn't manage to dereference any of the …
> feat: Support for locals referencing locals [CFG-1654]

- .snyk
This license is covered so we can safely ignore it permanently.
In this case there’s no problem in distributing the project using the MPL 2.0-governed code, on the basis that: (i) no modification has been made to the code; (ii) the unmodified code is in its own separate file, not inserted into another file; (iii) we comply with the notice and attribution requirements set out in section 3.1 of MPL 2.0 - by including the copyright notice attached to the code, telling users that the code is covered by MPL 2.0, and providing a link to the licence at https://www.mozilla.org/en-US/MPL/2.0/; and (iv) we make the MPL’d source code available alongside the binaries.
> MPL license should be ignored permanently

- terraform_plan.go
- Introduces a fix following a nil map assignment alert received ([thread](https://snyk.slack.com/archives/C023NA9FQCU/p1671343160064919))
It looks like we’re only checking if the conversion is possible here, not checking if the value is nil.
I tried simulating this here:
```
a := map[string]map[string]string{}
var b interface{} = a["test"]
if _, ok := b.(map[string]string); ok {
log.Println("A")
} else {
log.Println("B")
}
```
Based on the comments it looks like this was the intention. I’ll open a fix PR
> fix: nil resolved resources map

- terraform/variables.go
`mergeInputVariables()` determines the order for merging input variables by sorting a slice of file names by priority. The name of the files are extracted from the keys of a map, but iIterating over a map is not deterministic in Go. To make the implementation of `mergeInputVariables()` deterministic, and to prevent flakiness in `TestMergeVariablesFromTerraformFiles`, the slice of file names should be sorted before being sorted again by priority.
> fix: Merge input variables in a deterministic way

- hcl2.go
- hcl2_jsonencode_test.go
- testdata/terraform/jsonencode.tf
The `snyk` CLI uses the version of the Terraform parser implemented by the `terraform` package in this library. The `ParseHCL2` function, exported by this library and used by `snyk-iac-rules`, still uses plain `hcl2json`. 
Because of this difference, users of `snyk-iac-rules` and users of `snyk` don't have a consistent developer experience. A user writing a custom rule, and testing it via `snyk-iac-rules`, might be unable to run that rule in `snyk`. An example of this incompatibility is the handling of the `jsonencode` function in Terraform code. 
Given this input file:
```hcl
resource "aws_iam_role_policy" "test_policy" {
name = "test_policy"
role = aws_iam_role.test_role.id
policy = jsonencode({
Version = "2012-10-17"
Statement = [
{
Action = [
"ec2:*",
]
Effect   = "Allow"
Resource = …
```
> feat: Use the latest, custom Terraform parser

- .github/workflows/release.yml
Fixes the release workflow:
- Some GitHub actions are deprecated because they run on Node 12.
- `release-it` is unable to find `@release-it/conventional-changelog` when installed globally.
> fix: Upgrade GitHub actions and fix release-it installation

- .release-it.json
Configure release-it to skip publishing to NPM and reading the version from `package.json`.
> fix: Update release-it configuration
